version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: huntek
    restart: always
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge